### ISSUE TITLE
Deprecate repo

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-equinix-metal#136]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This provider was deprecated in favor of https://www.pulumi.com/registry/packages/equinix/ - https://github.com/equinix/pulumi-equinix [a while ago](https://github.com/pulumi/registry/pull/2475), but the README here still needs to be updated with that information and this repo should be archived.

- [x] Add deprecation note to README, with link to new provider repo
- [x] Remove provider from ci-management
- [x] Archive this repo

**Comment by guineveresaenger** [comment]
Clicking the Archive task before this issue goes unresponsive :joy:
