### ISSUE TITLE
Ability to list all devices in project without specifying each ID individually

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [pulumi/pulumi-equinix-metal#56]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to be able to programmatically query Equinix for all servers I have deployed in a project instead of having to store those separately. This would be a function like GetDevices which would take the ProjectID as input and list an array of Devices.

### Affected area/feature

Unknown, but presumably the connection between the API from Equinix and Pulumi would need to be modified to add this.

**Comment by stack72** [comment]
Hi @gidoBOSSftw5731 

Thanks for the request here - this is something we would need to get added upstream before we were able to add this as this provider is built from https://github.com/equinix/terraform-provider-metal

Paul

**Comment by gidoBOSSftw5731** [comment]
Made an issue in the terraform provider (new repo too, yay marketing) as was indicated above.
